image: docker:latest

services:
  - name: docker:23.0.1-dind
    command: ["--tls=false"] # Disable TLS for easier local debugging

variables:
  DOCKER_HOST: "tcp://docker:2375" # Connect to the Docker daemon
  DOCKER_TLS_CERTDIR: "" # Disable TLS, since it's not set up
  DOCKER_DRIVER: "overlay2"

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo "Waiting for Docker to start..."
    - until docker info; do sleep 3; done # Wait for Docker to be ready
    - echo "Docker is running!"
    - docker-compose build # Build all services
  only:
    - project

test:
  stage: test
  script:
    - echo "Running test phase"
  only:
    - project

deploy:
  stage: deploy
  script:
    - docker-compose up -d
    - echo "Deployment completed!"
  dependencies:
    - build
  only:
    - project
