image: docker:latest

services:
  - docker:20.10.21-dind

variables:
  DOCKER_TLS_CERTDIR: "" # Disable TLS because we use an insecure connection
  DOCKER_HOST: "tcp://docker:2375" # Set correct Docker host
  DOCKER_DRIVER: "overlay2"

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo "Waiting for Docker to be ready..."
    - until docker info; do sleep 1; done
    - echo "Docker is now ready!"
    - docker-compose build
  only:
    - project

test:
  stage: test
  script:
    - echo "Running test phase"
  only:
    - project

deploy:
  stage: deploy
  script:
    - docker-compose up -d
    - echo "Deployment completed!"
  dependencies:
    - build
  only:
    - project
