version: "3.5"

services:
  service1_instance1:
    build:
      context: ./service1
      dockerfile: Dockerfile
    expose:
      - "5000"
    environment:
      - NODE_ENV=development
    networks:
      - dev_network

  service1_instance2:
    build:
      context: ./service1
      dockerfile: Dockerfile
    expose:
      - "5000"
    environment:
      - NODE_ENV=development
    networks:
      - dev_network

  service1_instance3:
    build:
      context: ./service1
      dockerfile: Dockerfile
    expose:
      - "5000"
    environment:
      - NODE_ENV=development
    networks:
      - dev_network

  service2:
    build:
      context: ./service2
      dockerfile: Dockerfile
    expose:
      - "3000"
    environment:
      - NODE_ENV=development
    networks:
      - dev_network # Ensure service2 is on the same network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8198:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
    depends_on:
      - service1_instance1
      - service1_instance2
      - service1_instance3
      - service2
    networks:
      - dev_network

  tests:
    build:
      context: ./tests
      dockerfile: Dockerfile
    depends_on:
      - nginx
    environment:
      - NODE_ENV=test
    volumes:
      - ./tests:/tests
    working_dir: /tests
    command: ["npm", "test"]
    networks:
      - dev_network

networks:
  dev_network:
    driver: bridge
