version: "3.5"

services:
  service1_instance1:
    build:
      context: ./service1
      dockerfile: Dockerfile
    expose:
      - "5000"
    environment:
      - NODE_ENV=development
    networks:
      - devops_network

  service1_instance2:
    build:
      context: ./service1
      dockerfile: Dockerfile
    expose:
      - "5000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock" # 🚀 Allow container to execute Docker commands on the host
    environment:
      - NODE_ENV=development
    networks:
      - devops_network

  service1_instance3:
    build:
      context: ./service1
      dockerfile: Dockerfile
    expose:
      - "5000"
    environment:
      - NODE_ENV=development
    networks:
      - devops_network

  service2:
    build:
      context: ./service2
      dockerfile: Dockerfile
    expose:
      - "3000"
    environment:
      - NODE_ENV=development
    networks:
      - devops_network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8198:80"
    volumes:
      - ./nginx:/etc/nginx
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd

    depends_on:
      - service1_instance1
      - service1_instance2
      - service1_instance3
      - service2
    networks:
      - devops_network
  test-service:
    build:
      context: ./tests
      dockerfile: Dockerfile
    depends_on:
      - nginx
    environment:
      - API_URL=http://nginx/fetch
    volumes:
      - ./tests:/app
      - ./test-logs:/app/test-logs
    networks:
      - devops_network
networks:
  devops_network:
    driver: bridge
